app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("personal-prayer/", views.PersonalPrayerView.as_view(), name="personal-prayer"),
    path("delete-prayer-request/<pk>/", views.PrayerRequestDeleteView.as_view(), name="delete-prayer-request"),
    path("add-answered-prayer/<int:prayer_request_id>/", views.AddAnsweredPrayerView.as_view(), name="add-answered-prayer"),
    path("answered-prayer-list/", views.AnsweredPrayerListView.as_view(), name="answered-prayer-list"),
    path("register/", views.RegistrationView.as_view(), name="register"),
    path("prayer-request/", views.AddPrayerRequestView.as_view(), name="prayer-request"),
    path("create-group/", views.CreateGroupView.as_view(), name="create-group"),
    path("group-prayers/", views.GroupListView.as_view(), name="group-prayers"),
    path("group-prayers/<pk>/", views.GroupDetailView.as_view(), name="group-detail"),
    path("group-prayers/<int:group_id>/add-member/", views.AddMemberView.as_view(), name="add-member"),
]

list/urls.py
from django.contrib import admin
from django.contrib.auth import views
from app.views import NewLoginView
from django.urls import include, path

urlpatterns = [
    path("", include("app.urls")),
    path("admin/", admin.site.urls),
    path("login/", NewLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

app/templates/app/add-member.html
{% extends "app/navbar.html" %}
{% load static %}
{% block page-style %} <link href="{% static 'app/add-member.css' %}" rel="stylesheet"> {% endblock %}
{% block content %}

<div class="form-container">
  <form method="post" action="{% url 'app:add-member' group_id %}" class="add-member-form">
  {% csrf_token %}
    <h2>Add Member</h2>
    <div class="input">
      {% for field in form %}
      <label>{{ field.label }}</label>
      {{ field }}
      {% endfor %}
    </div>
    <button type='submit'>Submit</button>
    {% if messages %}
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    {% endif %}
  </form>
</div>


{% endblock %}

app/templates/app/answered-prayer-list.html
{% extends "app/base-list.html" %}

{% load static %}
{% load tz %}
{% block page-style %}<link href="{% static 'app/answered-prayer-list.css' %}" rel="stylesheet">{% endblock %}
{% block list-content %}
<div class="page-container">
    <div class="header">
        <h1>Answered Prayers</h1>
    </div>
    <blockquote class="bible-verse">"Ask and it will be given to you; seek and you will find; knock and the door will be opened to you."</blockquote>
    {% if page_obj %}
    {% for answered_prayer in page_obj %}
        <div class="answered-prayer">
            <div class="title-and-date">
                <p class="bold">Request</p>
                <p class="bold">{{answered_prayer.prayer_request.datetime|localtime|date:"M. j, Y" }}</p>
            </div>
            <br>
            <p>{{answered_prayer.prayer_request.content}} </p>
            <br>
            <div class="title-and-date">
                <p class="bold">Answer</p>
                <p class="bold">{{answered_prayer.datetime|localtime|date:"M. j, Y" }}</p>
            </div>
            <br>
            <p>{{answered_prayer.content}}</p>
        </div>
        
    {% endfor %}

    {% endif %}
</div>
{% endblock %}

app/templates/app/base-list.html
{% extends "app/navbar.html" %}

{% load static %}
{% block pagination-style %} <link href="{% static 'app/pagination.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
    <div class="flex-container">
        {% block list-content %}
        {% endblock %}

        <div class="pagination">
            <div class="previous">
                {% if page_obj.has_previous %}
                    <a href="?page={{page_obj.previous_page_number }}"><<</a>
                {% else %}
                    <p class="hidden"><<</p>
                {% endif %}
        
            </div>
        
            <div class="current-page">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </div>
        
            <div class="next">
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">>></a>
                {% else %}
                    <p class="hidden">>></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prayer Warrior</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'app/base.css' %}">
    {% block script %} {% endblock %}
    {% block navbar-style %} {% endblock %}
    {% block page-style %} {% endblock %}
    {% block pagination-style %} {% endblock %}
</head>
<body>
    <div id="page-container">
        <div class="navbar">
        {% block navbar %} {% endblock %}
        </div>
    
        <div id="content">
        {% block content %} {% endblock %}
        </div>
        
        <div id="footer">
        {% block footer %} {% endblock %}
        </div>
    </div>
</body>
</html>

app/templates/app/create-group.html
{% extends "app/navbar.html" %}
{% load static %}
{% block page-style %} <link href="{% static 'app/create-group.css' %}" rel="stylesheet"> {% endblock %}
{% block content %}

<div class="form-container">
    <form action="{% url 'app:create-group' %}" method="post" class="add-group-form">
    {% csrf_token %}
        <h2 class="form-item">Create Group</h2>
        <div class="input-box form-item">
            <label for="group-name">Group name:</label>
            <input type="text" name="name" id="group-name" required>    
        </div>
        <button type="submit" class="form-item">Submit</button>
        {% if messages %}
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        {% endif %}
    </form>
</div>


{% endblock %}

app/templates/app/group-detail.html
{% extends "app/navbar.html" %}

{% load static %}
{% block page-style %} <link rel="stylesheet" href="{% static 'app/group-detail.css' %}">{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="header">
            <h1>Group Prayer Requests</h1>
            <div class="buttons">
                <a href="{% url 'app:prayer-request' %}" class="add-button">
                  <i class="fa-solid fa-hands-praying"></i>
                  <div>Add prayer</div>
                </a>
                <a href="{% url 'app:add-member' group.id %}" class="add-button">
                  <i class="fa-solid fa-person"></i>
                  <div>Add member</div>
                </a>
            </div>
        </div>
        <blockquote class="bible-verse">"Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective."</blockquote>
        {% if prayer_list %}
        <ul class="flex-container">
        {% for prayer in prayer_list %}
            <li class="prayer-request">{{ prayer.content }}</li>
        {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

app/templates/app/group-list.html
{% extends "app/base-list.html" %}

{% load static %}
{% block page-style %}<link href="{% static 'app/group-list.css' %}" rel=stylesheet>{% endblock %}
{% block list-content %}
<div class="page-container">
    <div class="header">
        <h1>Prayer Groups</h1>
        <div class="buttons">
            <a href="{% url 'app:create-group' %}" class="add-button">
              <i class="fa-solid fa-users"></i>
              <div>Add group</div>
            </a>
        </div>
    </div>
    <blockquote class="bible-verse">"For where two or three gather in my name, there am I with them."</blockquote>
    {% if page_obj %}
    {% for group in page_obj %}    
    <ul class="flex-container">
        <a href="{% url 'app:group-detail' group.id %} ">
            <li class="group"> {{ group.name }} </li>
        </a>
    </ul>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/navbar.html" %}

{% load static %}
{% block page-style %} <link rel="stylesheet" href="{% static 'app/index.css' %}"> {% endblock %}

{% block content %}

<blockquote>"Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven. Give us today our daily bread. And forgive us our debts, as we also have forgiven our debtors. And lead us not into temptation, but deliver us from the evil one."</blockquote>

{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}
{% load static %}

{% block page-style %} <link href="{% static 'app/login.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
<div class="page-container">
    <div class="flex-container">
        <div class="logo">
            <h1>Prayer Warrior</h1>
            <div class="images">
                <img src="{% static 'app/images/cross.svg' %}" alt="cross" width="100px">
                <img src="{% static 'app/images/sword.svg' %}" alt="sword" width="100px">
            </div>
        </div>

        <div class="form-box">
            <form method="post" action="{% url 'login' %}" class="login-info">
            {% csrf_token %}
                <input type="text" name="username" id="username" placeholder="Username" class="flex-item" autofocus>
                <input type="password" name="password" id="password" placeholder="Password" class="flex-item">
                <button type="submit" class="flex-item">Log In</button>
                <input type="hidden" name="next" value="{{ next }}">
            </form>

            <hr>

            <a href="{% url 'app:register' %}"><button>Register</button></a>

            <div class="messages">
                {% if form.errors %}
                <p>Invalid username and password combination</p>
                {% endif %}

                {% if next %}
                    {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
                    
                    {% else %}
                    <p>Please login to see this page.</p>
                    {% endif %}
                {% endif %}

                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/navbar.html
{% extends "app/base.html" %}

{% load static %}

{% block navbar-style %}
<link rel="stylesheet" href="{% static 'app/navbar.css' %}">
{% endblock %}

{% block navbar %}
<header>
    <h1 id="nav-title"><a href="{% url 'app:index' %}">Prayer Warrior</a></h1>
    <button class="navbar-toggle" onclick="toggleMenu()"><i class="fas fa-bars"></i></button>
    <nav>
        <ul id="navbar-menu">
            <li><a href="{% url 'app:personal-prayer' %}">Personal Prayers</a></li>
            <li><a href="{% url 'app:group-prayers' %}">Group Prayers</a></li>
            <li><a href="{% url 'app:answered-prayer-list' %}">Answered Prayers</a></li>
            <li>
                <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                    <button type="submit" id="logout-button">Logout</button>
                </form>
            </li>
        </ul>
    </nav>
</header>

<script>
  function toggleMenu () {
    document.querySelector("#navbar-menu").classList.toggle('show');
  }
</script>
{% endblock %}

{% block footer %}
<footer>
    <ul>
        <li>Prayer Warrior</li>
        <li>2024</li>
    </ul>
</footer>
{% endblock %}

app/templates/app/personal-prayer.html
{% extends "app/base-list.html" %}

{% load static %}
{% load tz %}
{% block page-style %} <link rel="stylesheet" href="{% static 'app/personal-prayer.css' %}"> {% endblock %}
{% block script %}
    <script src="{% static 'app/javascript/delete-request.js' %}" defer></script>
{% endblock %}

{% block list-content %}
<div class="page-container">
    <div class="header">
        <h1>Personal Prayers</h1>
        <div class="buttons">
            <a href="{% url 'app:prayer-request' %}" class="add-button">
              <i class="fa-solid fa-hands-praying"></i>
              <div>Add prayer</div>
            </a>
        </div>
    </div>
    <blockquote class="bible-verse">"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God."</blockquote>
{% if prayer_request_list %}
    <div class="flex-container">
    {% for prayer_request in page_obj %}
        <div class="prayer-request" id="pr-{{ prayer_request.id }}">
            <div class="content-and-date">
              <p class="bold">Request</p>
              <p class="date bold">{{ prayer_request.datetime|localtime|date:"M. j, Y" }}</p>
            </div>
            <br>
            <p>{{ prayer_request.content }}</p>
            <button type="button" class="request-buttons delete-button" value="{{ prayer_request.id }}">
              <i class="fa-solid fa-trash"></i>
              <div>Delete</div>
            </button>
            <button type="button" class="request-buttons answered-prayer-button" value="{{ prayer_request.id }}">
              <i class="fa-solid fa-reply"></i>
              <div>Answer</div>
            </button>
        </div>

        <div id="delete-{{ prayer_request.id }}" class="modal">
            <div class="modal-content">
                <p>Are you sure you want to delete this prayer request?</p>
                <form method="post" action="{% url 'app:delete-prayer-request' prayer_request.id %}" class="confirmation-form">
                    {% csrf_token %}
                    <button type="submit">Yes</button>
                    <button type="button" class="no-button" value="{{ prayer_request.id }}">No</button>
                </form>
            </div>
        </div>

        <div id="add-answer-{{ prayer_request.id }}" class="modal">
            <div class="modal-content">
                <form method="post" action="{% url 'app:add-answered-prayer' prayer_request.id %}" class="confirmation-form">
                    {% csrf_token %}
                    <label for="answered-prayer-content" class="bold">Answer</label>
                    <textarea name="content" id="answered-prayer-content" rows="15" cols="75" autofocus></textarea>
                    <button type="submit">Submit</button>
                    <button type="button" class="cancel-button" value="{{ prayer_request.id }}">Cancel</button>
                </form>
            </div>
        </div>
    {% endfor %}
    </div>
{% endif %}
</div>
{% endblock %}

app/templates/app/prayer-request.html
{% extends "app/navbar.html" %}
{% load static %}

{% block script %}
    <script src="{% static 'app/javascript.js' %}"></script>
{% endblock %}

{% block page-style %} <link href="{% static 'app/prayer-request.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
<div class="form-container">
    <form action="{% url 'app:prayer-request' %}" method="post" id="prayer-request" class="prayer-request-form">
    {% csrf_token %}
        <h2>Add Prayer Request</h2>
        <!-- <div class="form-input">{{ form }}</div> -->
         {% for field in form %}
          <label class="label-class">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            {{ error }}
          {% endfor %}
        {% endfor %}
        <button type="submit" id="btn" onclick="disableButton()">Add prayer</button>
        {% if messages %}
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        {% endif %}
    </form>
</div>



{% endblock %}

app/templates/app/register.html
{% extends "app/base.html" %}
{% load static %}

{% block page-style %} <link href="{% static 'app/register.css' %}" rel="stylesheet"> {% endblock %}

{% block content %}
<div class="page-container">
    <div class="flex-container">
        <div class="logo">
            <h1>Prayer Warrior</h1>
            <div class="images">
                <img src="{% static 'app/images/cross.svg' %}" alt="cross" width="100px">
                <img src="{% static 'app/images/sword.svg' %}" alt="sword" width="100px">
            </div>
        </div>

        <div class="form-box">
            <form method="post" action="{% url 'app:register' %}" class="registration-info">
            {% csrf_token %}
                <input type="text" name="username" id="usernam" placeholder="Username" class="flex-item" autofocus>
                <input type="password" name="password1" id="password1" placeholder="Password" class="flex-item">
                <input type="password" name="password2" id="password2" placeholder="Confirm Password" class="flex-item">
                <button type="submit" class="flex-item">Register</button>
            </form>

            <div class="messages">
                {% if form.errors %}
                <p>Invalid username and password combination</p>
                {% endif %}

                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}